In [1]:
import numpy as np

In [2]:
#creating from lists
arr = np.array([1,2,3,4,5,6,7])
print(arr,type(arr),arr.dtype,arr.shape)
arr2 = np.array([1,2,3,4,5,6,"prime"])
print(arr2)
print(arr2.dtype)

[1 2 3 4 5 6 7] <class 'numpy.ndarray'> int64 (7,)
['1' '2' '3' '4' '5' '6' 'prime']
<U21


In [3]:
arr3 = arr.shape
print(type(arr3))

<class 'tuple'>


In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print("dimension of arry are:",arr_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension of arry are: (3, 3)


In [5]:
#creating from 
arr_2d2 = np.zeros((2,3),dtype = "int64") #prefill with zeros
print(arr_2d2)

[[0 0 0]
 [0 0 0]]


In [6]:
arr_2d3 = np.ones((2,2))
print(arr_2d3)

[[1. 1.]
 [1. 1.]]


In [7]:
arr_2d4 = np.full((2,2),34)
print(arr_2d4)

[[34 34]
 [34 34]]


In [8]:
arr_2d5 =np.eye(4)
print(arr_2d5)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
arr_2d6 = np.arange(1,11,2)
print(arr_2d6)

[1 3 5 7 9]


In [10]:
arr_2d7 = np.linspace(1,100,4)
print(arr_2d7)

[  1.  34.  67. 100.]
