In [1]:
import numpy as np

In [2]:
#properties of numpy
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
d_arr = arr.astype(np.float32)
print(d_arr,d_arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float32


In [3]:
#operations on numpy arrays
#reshaping
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
reshaped  = arr2.reshape((3,2))
print(reshaped)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [4]:
#operations on numpy arrays
#indexing
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1][1])

5


In [5]:
#operations on numpy arrays
#fancy indexing
arr = np.array([1,2,3,4,5,6,7])
print(arr[[1,2,6]])

[2 3 7]


In [6]:
#operations on numpy arrays
#boolean indexing
arr = np.array([5,7,4,9,8,2])
print(arr[arr > 3])
print(arr[arr % 2 == 0])

[5 7 4 9 8]
[4 8 2]


In [7]:
#operations on numpy arrays
#slicing
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:3])
print(arr[1:6:2])

[2 3]
[2 4 6]
