In [2]:
import numpy as np

In [28]:
# Two dimmensional array
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D)
print(np.sum(arr_2D))
print(arr_2D[1: ,1:])
print(np.sum(arr_2D,axis = 0))
print(np.sum(arr_2D,axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[[5 6]
 [8 9]]
[12 15 18]
[ 6 15 24]


In [35]:
# Three dimmensional array
arr= np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])     #2*3*2
print(arr)
print(arr.shape)
print(arr[0,1,0])
print(arr[0: , 0: ,0 ])
print(np.sum(arr,axis = 0))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3
[[ 1  3  5]
 [ 7  9 11]]
[[ 8 10]
 [12 14]
 [16 18]]
