In [1]:
import numpy as np

In [2]:
#vectorization
arr = np.array([1,2,3,4,5])
print(arr ** 2)
arr2 = np.array([6,7,8,9,10])
print(arr + arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [3]:
#broadcasting
arr = np.array([1,2,3,4,5])
print(arr + 5)
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr + arr2)

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]


In [7]:
#vector normalization
arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
standard_devation = np.std(arr)
print(mean)
print(standard_devation)
print("normalized array is:",(arr - mean)/standard_devation)

2.5
1.118033988749895
normalized array is: [[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
